apiVersion: v1
kind: Service
metadata:
  name: {{ include "plumb.fullname" . }}
  labels:
    {{- include "plumb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "plumb.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
